### ISSUE TITLE
LockOrientation not working on tablet

### ISSUE THREAD

**Issue by CarLoOSX** [wcoder/Xamarin.Plugin.DeviceOrientation#12]
Hello, I do this:

            if (Settings.OrientationSwitch)
            {
                DeviceOrientations selectedOrientation = Settings.Orientation == 0 ? DeviceOrientations.Portrait : DeviceOrientations.Landscape;

                CrossDeviceOrientation.Current.LockOrientation(selectedOrientation);
            }

Is working perfectly on iOS mobile, but is not working when I deploy to tablet devices. Any idea?

Thank you!

**Comment by wcoder** [comment]
Hi, thanks for the feedback! Could you give me additional info?

- Which device do you use (versions)?
- Xamarin.Forms or Xamarin iOS Native?

**Comment by CarLoOSX** [comment]
Hello!

As far as I know is not working in iPad Air 2 and later. I think that is working in iPad 1 but I can not remeber so well.

I’m using your plugin in both platforms native and forms, in fact I’m using native forms switching between 2 platforms.

Thank you so much!

**Comment by CarLoOSX** [comment]
Is working. 
It was my fault !!!
You should chek in info.plist: **Requires fullscreen** 
Thank you so much!
