### ISSUE TITLE
How can I set to default the orientation of the App to Landscape?

### ISSUE THREAD

**Issue by christianquirante** [wcoder/Xamarin.Plugin.DeviceOrientation#15]
How can I set to default the orientation of the App to Landscape? then actually just locking and never allowing the user to put the app into portrait mode?

**Comment by wcoder** [comment]
Hi, what platform? or Forms?

If you want to lock orientation on the whole app you need to use platform-specific practice, like this: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/device-orientation?tabs=vswin (just select supported orientation what you want)

**Comment by christianquirante** [comment]
Thanks for pointing this out for me, you were really helpful!
