### ISSUE TITLE
Add ability to change orientation in runtime

### ISSUE THREAD

**Issue by wcoder** [wcoder/Xamarin.Plugin.DeviceOrientation#2]
- [x] Android
- [x] iOS
- [x] UWP

**Comment by LPAMNijoel** [comment]
Does your project support being able to keep its supported landscape onResume? or on background. like if the user press the home button and put it in the background(e.g.)

**Comment by wcoder** [comment]
Yes, orientation position is preserve.

**Comment by LPAMNijoel** [comment]
May, I ask for a example please? or, some guidance. I been searching for a example or some guidance on how to implement this. basically, what i'm trying to implement is i have my application in fully landscape mode which is what i want. however, when the application goes to the background(OnSleep) things are okay however, when i want to load the application back up(OnResume) then, the application breaks out of landscape mode and goes into portrait mode. That's what I'm stuck on.
