### ISSUE TITLE
Lock Orientation not working in xamarin forms 

### ISSUE THREAD

**Issue by arjun159** [wcoder/Xamarin.Plugin.DeviceOrientation#3]
When using the lockorientation to portrait in xamarin forms even then the screen is rotating to the landscape mode.

**Comment by wcoder** [comment]
Could you please clarify for Android / iOS / UWP?

**Comment by gmwilhelm** [comment]
I see this too, on iOS

**Comment by wcoder** [comment]
Did you use the code for iOS Specific Support?
https://github.com/wcoder/Xamarin.Plugin.DeviceOrientation#ios-specific-support

**Comment by gmwilhelm** [comment]
I don't have a ViewController in Xamarin.Forms on iOS.

I'm trying like this in my code-behind of my xaml page:

```
 public partial class MyLockedPage : ContentPage
    {
        public MyLockedPage ()
        {
            InitializeComponent();
            CrossDeviceOrientation.Current.LockOrientation(Plugin.DeviceOrientation.Abstractions.DeviceOrientations.Portrait);
        }
    }
```

**Comment by wcoder** [comment]
Ok, I will check and report results in the near time.

**Comment by wcoder** [comment]
@arjun159, @gmwilhelm please check version 1.0.5.

For Xamarin.Forms iOS look at this: https://github.com/wcoder/Xamarin.Plugin.DeviceOrientation#xamarinforms-ios

**Comment by gmwilhelm** [comment]
Thanks, works for me

**Comment by DarrenMcGrath** [comment]
For me on iOS I had to manually edit the Info.plist as the Manifest editor was not updating it correctly
See below for locking iphone and ipad to portrait 

```

<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
	</array>
```

**Comment by vhugogarcia** [comment]
Thanks @darrenmcgrath the info.plist solution worked very good.

**Comment by ravi-simrun** [comment]
we are facing a weird issue with xamarin forms ios orientation.

while implementing the xamarin community toolkit we are facing the orientation issue in ios.

In android, it is working fine but in ios the tool kit tab view is messed up.

Any solution?

**Comment by yauhenipakala** [comment]
@ravi-simrun could you please provide more info?

- what is the issue?
- Xamarin.Forms version?
- Xamarin community toolkit version?
- sample app or any additional info

**Comment by ravi-simrun** [comment]
ya sure please find the attached screenshots 
Xamarin.Forms version 5.0.0.2196
Xamarin community toolkit version [1.3.1]
![IMG_0034](https://user-images.githubusercontent.com/95903172/145935825-11c6926d-6a5c-4822-94a7-13e024d1f11e.PNG)
![IMG_0035](https://user-images.githubusercontent.com/95903172/145935829-3ef6a882-405c-4734-bcbb-c73008f0ac52.PNG)
![IMG_0036](https://user-images.githubusercontent.com/95903172/145935830-319dfead-26c7-4196-9090-40c84a73476f.PNG)

**Comment by yauhenipakala** [comment]
@ravi-simrun thanks for the details
could you please describe the issue? (screenshots are not so clear) code samples?
