### ISSUE TITLE
Portrait and landscape orientations are opposite of expected 

### ISSUE THREAD

**Issue by philipogorman** [wcoder/Xamarin.Plugin.DeviceOrientation#5]
I am testing on a real device and an emulator on android, the library picks up the orientation change ok but the but the orientation detected is opposite of what is expected.
"Plugin.DeviceOrientation" version="1.0.5"

**Comment by wcoder** [comment]
Hi @philipogorman! Thanks for your feedback!

What Android version of your emulator/real device do you use?

**Comment by philipogorman** [comment]
Simulator: Android_Accelerated_Nougaut(Android 7.1 -API 25)
Device: ASUS P028 Android 7.0

**Comment by avinashramireddy-rapidd** [comment]
Any update?

Also OrientationChanged is hitting many times(lost count-50+ or more I don't know...) while debugging.

**Comment by wcoder** [comment]
Thanks for your feedback! Currently, I will try to reproduce it (orientation detected is opposite).

created issue #6

**Comment by wcoder** [comment]
@philipogorman  do you use a plugin in Xamarin.Forms or native Xamarin Android app?

**Comment by wcoder** [comment]
Again, I checked the last version of the plugin on different Android versions, on emulators and devices.

The plugin works correctly.

I will close that issue, but if you have more information about this, please write me.
